<?php

/**
 * Code-derived reference for the AI assistant (settings, admin screens, Free/PRO).
 *
 * Generated by tools/build-ai-reference.php from the plugin source on every
 * release; ranks above the Help Scout docs, below live site data from tools.
 */
class SLN_AI_Reference
{
	const RELATIVE_FILE = '/src/SLN/AI/data/ai-reference.json';

	/** @var array|null|false false = not loaded yet */
	private static $data = false;

	/**
	 * @return string
	 */
	public static function file()
	{
		$root = defined('SLN_PLUGIN_DIR') ? SLN_PLUGIN_DIR : dirname(dirname(dirname(__DIR__)));

		return (string) apply_filters('sln_ai_reference_file', $root . self::RELATIVE_FILE);
	}

	/**
	 * @return array|null Null when the file was not generated for this build.
	 */
	public static function data()
	{
		if (self::$data !== false) {
			return self::$data;
		}
		self::$data = null;
		$file       = self::file();
		if (is_readable($file)) {
			$decoded = json_decode((string) file_get_contents($file), true);
			if (is_array($decoded) && isset($decoded['settings']) && is_array($decoded['settings'])) {
				self::$data = $decoded;
			}
		}

		return self::$data;
	}

	/**
	 * Test hook: inject a reference array (null resets to the file).
	 *
	 * @param array|null $data
	 */
	public static function setData($data)
	{
		self::$data = is_array($data) ? $data : false;
	}

	/**
	 * @return bool
	 */
	public static function isAvailable()
	{
		return self::data() !== null;
	}

	/**
	 * @return array plugin_version, generated_at, edition, stale
	 */
	public static function meta()
	{
		$data    = self::data();
		$version = $data && isset($data['plugin_version']) ? (string) $data['plugin_version'] : '';

		return array(
			'plugin_version' => $version,
			'generated_at'   => $data && isset($data['generated_at']) ? (string) $data['generated_at'] : '',
			'edition'        => $data && isset($data['edition']) ? (string) $data['edition'] : '',
			'stale'          => $data && defined('SLN_VERSION') && $version !== '' && $version !== SLN_VERSION,
		);
	}

	/**
	 * @param string $key
	 * @return array|null
	 */
	public static function findSetting($key)
	{
		$data = self::data();
		if (! $data) {
			return null;
		}
		$key = (string) $key;
		foreach ($data['settings'] as $row) {
			if (isset($row['key']) && $row['key'] === $key) {
				return $row;
			}
		}

		return null;
	}

	/**
	 * Keyword search across settings, screens and features.
	 *
	 * @param string $query
	 * @param string $kind  setting|screen|feature|'' (all)
	 * @param int    $limit
	 * @return array<int,array> Rows with a 'kind' key.
	 */
	public static function search($query, $kind = '', $limit = 8)
	{
		$data = self::data();
		if (! $data) {
			return array();
		}
		$limit  = max(1, min(20, (int) $limit));
		$needle = self::normalize($query);
		$tokens = array_values(
			array_filter(
				preg_split('/[\s_\-]+/', $needle),
				function ($t) {
					return strlen($t) >= 3;
				}
			)
		);

		$pools = array(
			'setting' => isset($data['settings']) ? $data['settings'] : array(),
			'screen'  => isset($data['screens']) ? $data['screens'] : array(),
			'feature' => isset($data['features']) ? $data['features'] : array(),
		);

		$scored = array();
		foreach ($pools as $poolKind => $rows) {
			if ($kind !== '' && $kind !== $poolKind) {
				continue;
			}
			foreach ((array) $rows as $row) {
				$id    = isset($row['key']) ? $row['key'] : ( isset($row['id']) ? $row['id'] : ( isset($row['slug']) ? $row['slug'] : '' ) );
				$score = self::score($row, (string) $id, $needle, $tokens);
				if ($score > 0) {
					$row['kind']   = $poolKind;
					$row['_score'] = $score;
					$scored[]      = $row;
				}
			}
		}

		usort(
			$scored,
			function ($a, $b) {
				return $b['_score'] - $a['_score'];
			}
		);
		$scored = array_slice($scored, 0, $limit);
		foreach ($scored as &$row) {
			unset($row['_score']);
		}

		return $scored;
	}

	/**
	 * Settings whose current value must never reach the model.
	 *
	 * @param string $key
	 * @return bool
	 */
	public static function isSecretKey($key)
	{
		return (bool) preg_match('/(secret|password|passwd|token|api_?key|_key$|^key_|sid$|account|auth|private|webhook|client_id|license)/i', (string) $key);
	}

	/**
	 * @param string|null $path Relative admin path stored in the reference.
	 * @return string|null
	 */
	public static function url($path)
	{
		if ($path === null || $path === '') {
			return null;
		}

		return function_exists('admin_url') ? admin_url($path) : $path;
	}

	/**
	 * @param array  $row
	 * @param string $id
	 * @param string $needle
	 * @param array  $tokens
	 * @return int
	 */
	private static function score(array $row, $id, $needle, array $tokens)
	{
		if ($needle === '') {
			return 0;
		}
		$score = 0;
		if (strtolower($id) === $needle) {
			$score += 100;
		}

		$parts = array($id);
		foreach (array('label', 'title', 'section', 'tab_label', 'help', 'description', 'tab') as $field) {
			if (! empty($row[ $field ]) && is_string($row[ $field ])) {
				$parts[] = $row[ $field ];
			}
		}
		if (! empty($row['allowed']) && is_array($row['allowed'])) {
			foreach ($row['allowed'] as $opt) {
				if (! empty($opt['label']) && is_string($opt['label'])) {
					$parts[] = $opt['label'];
				}
			}
		}
		$hay = self::normalize(implode(' ', $parts));

		if (strpos($hay, $needle) !== false) {
			$score += 40;
		}
		foreach ($tokens as $tok) {
			if (strpos($hay, $tok) !== false) {
				$score += 10;
			}
		}

		return $score;
	}

	/**
	 * @param string $text
	 * @return string
	 */
	private static function normalize($text)
	{
		$text = class_exists('SLN_AI_Language') ? SLN_AI_Language::fold((string) $text) : (string) $text;

		return trim(strtolower($text));
	}
}
