<?php
// phpcs:ignoreFile WordPress.WP.I18n.TextDomainMismatch

namespace SLB_PWA;

class LabelProvider
{
    protected $labels;

    private static $instance;

    public static function getInstance(): LabelProvider
    {
        if (!self::$instance) {
            self::$instance = new self;
        }

        return self::$instance;
    }

    public function __construct()
    {
        $this->labels = array(
            'pendingPaymentStatusLabel' => __('Pending payment', 'salon-booking-system'),
            'pendingStatusLabel' => __('Pending', 'salon-booking-system'),
            'paidStatusLabel' => __('Paid', 'salon-booking-system'),
            'payLaterStatusLabel' => __('Pay later', 'salon-booking-system'),
            'errorStatusLabel' => __('Error', 'salon-booking-system'),
            'canceledStatusLabel' => __('Canceled', 'salon-booking-system'),
            'confirmedStatusLabel' => __('Confirmed', 'salon-booking-system'),
            'upcomingReservationsTitle' => __('Upcoming', 'salon-booking-system'),
            'upcomingReservationsNoResultLabel' => __('No upcoming bookings ...', 'salon-booking-system'),
            'upcomingBookingsScrollAriaLabel' => __('Upcoming bookings', 'salon-booking-system'),
            'upcomingPromosSectionTitle' => __('Features & add-ons', 'salon-booking-system'),
            'upcomingPromoCtaLabel' => __('Learn more', 'salon-booking-system'),
            'upcomingPromo1Title' => __('Dynamic pricing', 'salon-booking-system'),
            'upcomingPromo1Body' => __('Offer demand-based pricing with the Dynamic Pricing add-on for Salon Booking System.', 'salon-booking-system'),
            'upcomingPromo2Title' => __('SMS notifications', 'salon-booking-system'),
            'upcomingPromo2Body' => __('Send automated text reminders and cut no-shows with the right messaging add-on.', 'salon-booking-system'),
            'upcomingPromo3Title' => __('Full mobile workflow', 'salon-booking-system'),
            'upcomingPromo3Body' => __('Unlock the calendar, customers, and full booking details in this app with PRO.', 'salon-booking-system'),
            'label8Hours' => __('8 hrs', 'salon-booking-system'),
            'label24Hours' => __('24 hrs', 'salon-booking-system'),
            'label3Days' => __('3 days', 'salon-booking-system'),
            'label1Week' => __('1 week', 'salon-booking-system'),
            'allTitle' => __('All', 'salon-booking-system'),
            'deleteBookingConfirmText' => __('Are you sure ?', 'salon-booking-system'),
            'deleteBookingButtonLabel' => __('Yes, delete', 'salon-booking-system'),
            'deleteBookingGoBackLabel' => __('Go back', 'salon-booking-system'),
            'editReservationTitle' => __('Edit the reservation', 'salon-booking-system'),
            'dateTitle' => __('date', 'salon-booking-system'),
            'timeTitle' => __('time', 'salon-booking-system'),
            'customerFirstnamePlaceholder' => __('firstname', 'salon-booking-system'),
            'customerLastnamePlaceholder' => __('lastname', 'salon-booking-system'),
            'customerEmailPlaceholder' => __('email', 'salon-booking-system'),
            'customerAddressPlaceholder' => __('address', 'salon-booking-system'),
            'customerPhonePlaceholder' => __('phone', 'salon-booking-system'),
            'customerNotesPlaceholder' => __('notes', 'salon-booking-system'),
            'customerPersonalNotesPlaceholder' => __('customer personal notes', 'salon-booking-system'),
            'customerPersonalNotesLabel' => __('Customer personal notes', 'salon-booking-system'),
            'bookingLanguageLabel' => __('Email language', 'salon-booking-system'),
            'bookingLanguageHelp' => __('Language used for this customer\'s confirmation and reminder emails', 'salon-booking-system'),
            'saveAsNewCustomerLabel' => __('Save this customer', 'salon-booking-system'),
            'extraInfoLabel' => __('Extra info', 'salon-booking-system'),
            'addAndManageDiscountButtonLabel' => __('Add and manage discount', 'salon-booking-system'),
            'selectDiscountLabel' => __('Select a discount', 'salon-booking-system'),
            'addDiscountButtonLabel' => __('Add a discount', 'salon-booking-system'),
            'saveButtonLabel' => __('Save booking', 'salon-booking-system'),
            'savedLabel' => __('Saved', 'salon-booking-system'),
            'validationMessage' => __('Please fill the required fields', 'salon-booking-system'),
            'selectServicesPlaceholder' => __('Select services', 'salon-booking-system'),
            'selectAttendantsPlaceholder' => __('Select an assistant', 'salon-booking-system'),
            'selectResourcesPlaceholder' => __('Select a resource', 'salon-booking-system'),
            'selectServicesSearchPlaceholder' => __('Type service name', 'salon-booking-system'),
            'selectAssistantsSearchPlaceholder' => __('Type assistant name', 'salon-booking-system'),
            'selectResourcesSearchPlaceholder' => __('Type resource name', 'salon-booking-system'),
            'selectDiscountsSearchPlaceholder' => __('Type discount name', 'salon-booking-system'),
            'addServiceButtonLabel' => __('Add a service', 'salon-booking-system'),
            'addServiceMessage' => __('Please add services', 'salon-booking-system'),
            'selectExistingClientButtonLabel' => __('Select existing client', 'salon-booking-system'),
            'bookingDetailsTitle' => __('Booking details', 'salon-booking-system'),
            'totalTitle' => __('Total', 'salon-booking-system'),
            'transactionIdTitle' => __('Transaction ID', 'salon-booking-system'),
            'discountTitle' => __('Discount', 'salon-booking-system'),
            'depositTitle' => __('Deposit', 'salon-booking-system'),
            'dueTitle' => __('Due', 'salon-booking-system'),
            'editButtonLabel' => __('Edit booking', 'salon-booking-system'),
            'reservationsCalendarTitle' => __('Reservations calendar', 'salon-booking-system'),
            'noResultTimeslotsLabel' => __('No timeslots ...', 'salon-booking-system'),
            'addReservationTitle' => __('Add the reservation', 'salon-booking-system'),
            'customersAddressBookTitle' => __('Customers', 'salon-booking-system'),
            'goBackButtonLabel' => __('GO BACK', 'salon-booking-system'),
            'customersAddressBookNoResultLabel' => __('No customers found ...', 'salon-booking-system'),
            'installPWAPromptText' => __('Add to home screen ?', 'salon-booking-system'),
            'calendarLocale' => $lang = substr( get_locale(), 0, 2 ),
            'installPWAPromptInstallBtnLabel' => __('Install!', 'salon-booking-system'),
            'installPWAPromptNoInstallBtnLabel' => __('No, thanks', 'salon-booking-system'),
            'installPWAIOSText' => __('Install this app on your IPhone=> __( tap menu and then Add to homescreen',
                'salon-booking-system'),
            'shopsTitle' => __('Select a shop', 'salon-booking-system'),
            'shopsNoResultLabel' => __('No shops ...', 'salon-booking-system'),
            'shopTitleLabel' => __('Shop', 'salon-booking-system'),
            'selectShopFirstMessage' => __('Please select a shop first to edit booking', 'salon-booking-system'),
            'selectShopPlaceholder' => __('Select shop', 'salon-booking-system'),
            'successMessagePayRemainingAmount' => __('Email sent', 'salon-booking-system'),
            'errorMessagePayRemainingAmount' => __('Error, email not sent', 'salon-booking-system'),
            'takePhotoButtonLabel' => __('Take Photo', 'salon-booking-system'),
            'selectPhotoButtonLabel' => __('Select from phone', 'salon-booking-system'),
            'backImagesButtonLabel' => __('Go back', 'salon-booking-system'),
            'photoCameraButtonLabel' => __('Photo', 'salon-booking-system'),
            'customerDetailsUpdateButtonLabel' => __('Update customer', 'salon-booking-system'),
            'customerDetailsGoBackButtonLabel' => __('Go back', 'salon-booking-system'),
            'assistantBusyTitle' => __('Assistant is busy', 'salon-booking-system'),
            'assistantBusyMessage' => __('is busy from %s to %s. Please select another time or assistant.', 'salon-booking-system'),
            'attendantViewLabel' => __('Assistants view', 'salon-booking-system'),
            'bookingActionEdit' => __('Edit', 'salon-booking-system'),
            'bookingActionDelete' => __('Delete', 'salon-booking-system'),
            'bookingActionCallCustomer' => __('Call customer', 'salon-booking-system'),
            'bookingActionWhatsappCustomer' => __('Whatsapp customer', 'salon-booking-system'),
            'bookingActionOpenProfile' => __('Open customer profile', 'salon-booking-system'),
            'proUpgradeModalTitle' => __('PRO feature', 'salon-booking-system'),
            'proUpgradeModalMessage' => __('The calendar and customers directory are available in Salon Booking System PRO. Upgrade to unlock them in the mobile app.', 'salon-booking-system'),
            'proUpgradeModalCtaLabel' => __('View PRO plans', 'salon-booking-system'),
            'proUpgradeModalCloseLabel' => __('Not now', 'salon-booking-system'),
            'proUpgradeBookingDetailsMessage' => __('Opening a booking to view or edit details is available in Salon Booking System PRO. Upgrade to unlock full mobile booking management.', 'salon-booking-system'),
            'pwaLicensePromoFreeProTitle' => __('Unlock Salon Booking PRO', 'salon-booking-system'),
            'pwaLicensePromoFreeProBody' => __('Payments, deposits, SMS, advanced calendar, and the full mobile app workflow — upgrade to a PRO license on our website.', 'salon-booking-system'),
            'pwaLicensePromoFreeProCta' => __('View PRO plans', 'salon-booking-system'),
            'pwaLicensePromoBasicBusinessTitle' => __('Upgrade to Business Plan', 'salon-booking-system'),
            'pwaLicensePromoBasicBusinessBody' => __('Your Basic plan is active. Move up to Business for more included add-ons, higher limits, and advanced features for growing salons.', 'salon-booking-system'),
            'pwaLicensePromoBasicBusinessCta' => __('Compare plans', 'salon-booking-system'),
            'soapNotesTitle' => __('SOAP Notes', 'salon-booking-system'),
            'soapNotesEmpty' => __('No SOAP notes yet', 'salon-booking-system'),
            'soapNotesFillButton' => __('Fill SOAP notes', 'salon-booking-system'),
            'soapNotesEditButton' => __('Edit SOAP notes', 'salon-booking-system'),
            'soapNotesSaveButton' => __('Save notes', 'salon-booking-system'),
            'soapNotesSavedLabel' => __('SOAP notes saved', 'salon-booking-system'),
            'soapNotesErrorLabel' => __('Could not save SOAP notes', 'salon-booking-system'),
            'soapNotesLoadError' => __('Could not load SOAP notes', 'salon-booking-system'),
            'soapNotesAddPin' => __('Add note', 'salon-booking-system'),
            'soapNotesClearPins' => __('Clear all notes', 'salon-booking-system'),
            'soapNotesNewPin' => __('New note', 'salon-booking-system'),
            'soapNotesPinPlaceholder' => __('Note', 'salon-booking-system'),
            'bookingActionSoapNotes' => __('SOAP notes', 'salon-booking-system'),
            'soapNotesVoiceStart' => __('Speak', 'salon-booking-system'),
            'soapNotesVoiceStop' => __('Stop', 'salon-booking-system'),
            'soapNotesVoiceListening' => __('Listening… tap Stop when you are done', 'salon-booking-system'),
            'soapNotesVoiceUnsupported' => __('Voice input is not supported in this browser. Try Chrome or Safari.', 'salon-booking-system'),
            'soapNotesVoiceDenied' => __('Microphone permission was denied.', 'salon-booking-system'),
            'soapNotesVoiceNetwork' => __('Voice input needs a network connection in this browser.', 'salon-booking-system'),
            'soapNotesVoiceError' => __('Could not start voice input.', 'salon-booking-system'),
            'soapNotesPhotosTitle' => __('Visit photos', 'salon-booking-system'),
            'soapNotesPhotosHint' => __('Saved immediately — you do not need to tap Save notes', 'salon-booking-system'),
            'soapNotesTakePhoto' => __('Take photo', 'salon-booking-system'),
            'soapNotesChoosePhoto' => __('Choose from library', 'salon-booking-system'),
            'soapNotesPhotoCaption' => __('Caption', 'salon-booking-system'),
            'soapNotesPhotoDelete' => __('Delete photo', 'salon-booking-system'),
            'soapNotesPhotoUploadError' => __('Could not upload photo', 'salon-booking-system'),
            'soapNotesPhotoEmpty' => __('No photos yet', 'salon-booking-system'),
            'soapNotesStandingTitle' => __('Standing notes', 'salon-booking-system'),
            'soapNotesStandingHint' => __('Saved on this customer and shown on every visit', 'salon-booking-system'),
            'soapNotesStandingChip' => __('Every visit', 'salon-booking-system'),
            'soapNotesStandingPlaceholder' => __('Allergies, contraindications, ongoing plan…', 'salon-booking-system'),
            'soapNotesStandingSaved' => __('Standing notes saved', 'salon-booking-system'),
            'soapNotesCopyLastVisit' => __('Copy from last visit', 'salon-booking-system'),
            'soapNotesCopyLastVisitDated' => __('Copy from last visit ({date})', 'salon-booking-system'),
            'soapNotesCopyHint' => __('Fills this visit only. Does not copy photos or standing notes.', 'salon-booking-system'),
            'soapNotesCopyConfirm' => __('Replace this visit’s SOAP notes with the notes from {date}?', 'salon-booking-system'),
            'soapNotesCopyError' => __('Could not copy previous notes', 'salon-booking-system'),
        );
    }

    public function getLabels(): array
    {
        return $this->labels;
    }
}